import './globals.css'
import { Inter } from 'next/font/google'
import 'react-grid-layout/css/styles.css'
import 'react-resizable/css/styles.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-blue-50')}>{children}</body>
    </html>
  )
}
